version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: luminote-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: luminote
      MYSQL_USER: luminote_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
